apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch

spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.10.2
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch

spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash

spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:8.10.2
        ports:
        - containerPort: 5044
---
apiVersion: v1
kind: Service
metadata:
  name: logstash

spec:
  selector:
    app: logstash
  ports:
  - port: 5044
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:8.10.2
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
        ports:
        - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana

spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
  - port: 5601
