apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: healthcare-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # rootpassword in base64
  MYSQL_PASSWORD: cGFzc3dvcmQ= # password in base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: healthcare-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: healthcare
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: healthcare-ns
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
