---
# tasks file for deploy-app
- name: Create temporary directory for deployments
  tempfile:
    state: directory
    suffix: app_deploy
  register: temp_deploy_dir
  delegate_to: localhost
  become: no

- name: Copy backend deployment manifest with image replacement
  copy:
    content: "{{ lookup('file', '../../../k8s/backend-deployment.yaml') | replace('__BACKEND_IMAGE__', backend_image) }}"
    dest: "{{ temp_deploy_dir.path }}/backend-deployment.yaml"
  delegate_to: localhost
  become: no

- name: Copy frontend deployment manifest with image replacement
  copy:
    content: "{{ lookup('file', '../../../k8s/frontend-deployment.yaml') | replace('__FRONTEND_IMAGE__', frontend_image) }}"
    dest: "{{ temp_deploy_dir.path }}/frontend-deployment.yaml"
  delegate_to: localhost
  become: no

- name: Apply Backend Deployment
  k8s:
    state: present
    namespace: "{{ namespace }}"
    src: "{{ temp_deploy_dir.path }}/backend-deployment.yaml"

- name: Apply Frontend Deployment
  k8s:
    state: present
    namespace: "{{ namespace }}"
    src: "{{ temp_deploy_dir.path }}/frontend-deployment.yaml"

- name: Remove temporary directory
  file:
    path: "{{ temp_deploy_dir.path }}"
    state: absent
  delegate_to: localhost
  become: no
